export const site = {
  name: "Emel Senemoglu",
  brokerTitle: "Director Client Journey / Mortgage Broker",
  brokerage: "Powerhaus Mortgages — Dominion Lending Centres National Ltd.",
  shortBrokerage: "Powerhaus Mortgages · DLC National",
  url: "https://emelsenemoglu.ca",
  domain: "emelsenemoglu.ca",
  description:
    "Greater Vancouver mortgage broker Emel Senemoglu helps homebuyers, renewers, investors and newcomers across BC and Canada secure the right mortgage with personalized guidance.",
  tagline: "Mortgages built around your life, not the bank's.",
  email: "emel@emelsenemoglu.ca",
  secondaryEmail: "emel@powerhausmortgages.ca",
  emails: ["emel@emelsenemoglu.ca", "emel@powerhausmortgages.ca"],
  phone: "778-885-6609",
  phoneHref: "tel:+17788856609",
  whatsappHref: "https://wa.me/17788856609",
  address: {
    region: "Greater Vancouver, British Columbia",
    country: "Canada",
  },
  serviceArea: [
    "Vancouver",
    "Burnaby",
    "Richmond",
    "Surrey",
    "Coquitlam",
    "North Vancouver",
    "West Vancouver",
    "New Westminster",
    "Port Moody",
    "Langley",
    "Delta",
    "White Rock",
    "Maple Ridge",
    "Pitt Meadows",
    "Tsawwassen",
  ],
  social: {
    linkedin: "https://www.linkedin.com/",
    instagram: "https://www.instagram.com/",
    facebook: "https://www.facebook.com/",
  },
  license: {
    number: "MB608816",
    authority: "BCFSA",
    authorityFull: "British Columbia Financial Services Authority",
    act: "Mortgage Brokers Act",
    type: "Registration",
    effectiveDate: "2025-06-05",
    portalUrl: "https://portal.bcfsa.ca/",
  },
  licenseDisclaimer:
    "Emel Senemoglu is a licensed mortgage broker in British Columbia, registered with the BC Financial Services Authority (BCFSA #MB608816) under the Mortgage Brokers Act, operating through Powerhaus Mortgages — Dominion Lending Centres National Ltd.",
};

export type SiteConfig = typeof site;
